# Generated by Django 5.1 on 2024-09-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_product_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
    ]
